---
title: "GDD predictions"
author: "Victor, Lizzie"
date: "2024-08-26"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(terra) # process raster data
library(dplyr)
library(ggplot2)
library(ggforce) # geom_link2 function
library(scales) # date on x-axis
library(mgcv) # gam

wd <- "C:/Users/vandermeersch/Documents/CEFE/projects/synchrony"

# Data from Journe et al. 2024 ()
## note that this is the filtered dataset used by V. Journe, we may want to start from scratch with raw MasTree data
journe_d <- read.csv(file.path(wd, "data/journe2024", "mastree_subset_fagus.csv")) 

```

```{r gdd_classic}

process_data <- readRDS(file.path(wd, "data/processed", "journe2024_replicate.rds"))

datac <- 
  data.frame(site = process_data$sitenewname,
             latitude = process_data$Latitude,
             year = process_data$Year,
             date = process_data$Date,
             tmean = process_data$Tmean)

gdd_data <- datac %>%
  dplyr::group_by(site, year) %>%
  dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5, tmean, 0),
                gdd = cumsum(tmean_filt)) %>%
  dplyr::select(-tmean_filt) %>%
  ungroup() %>%
  mutate(doy = as.numeric(strftime(date, format = "%j")),
         source = stringr::str_split(site, "_", simplify = T)[, 1])

```

## Start of season

```{r compute_sos}

gdd_data <- gdd_data %>%
  dplyr::group_by(site, year) %>%
  dplyr::mutate(ab5 = zoo::rollapplyr(as.numeric(tmean>=5), 5, sum, fill = 0),
                sos = first(doy[ab5 == 5])) %>%
  ungroup()

# order according to latitude
gdd_data$site <- factor(x = gdd_data$site, 
                        levels = unique(gdd_data$site[order(gdd_data$latitude)]))



```

## End of season

```{r example_eos1}

ex_data <- gdd_data %>% 
               filter(site == "6013_15_FAGSYL" & year == 1987)

fit.lm <- lm(tmean ~ cos(2*pi*doy/365) + sin(2*pi*doy/365), data = ex_data)

time <- 1:365
pred <- predict(fit.lm, newdata = list(doy = time))    

plot(tmean ~ doy, data = ex_data, 
     xlim = c(1, 365), ylim = c(-30, 30))
lines(pred ~ time, col = "blue")

fderiv <- diff(pred)/diff(time)
lines(fderiv*100 ~ time[2:365], col = "red")
abline(v=as.numeric(which(fderiv == min(fderiv))), col="green")
abline(v=unique(ex_data$sos), col="green")

```

```{r example_eos2}

ex_data <- gdd_data %>% 
               filter(site == "413_1_FAGSYL" & year == 2003)

fit.lm <- lm(tmean ~ cos(2*pi*doy/365) + sin(2*pi*doy/365), data = ex_data)

time <- 1:365
pred <- predict(fit.lm, newdata = list(doy = time))    

plot(tmean ~ doy, data = ex_data, 
     xlim = c(1, 365), ylim = c(-30, 30))
lines(pred ~ time, col = "blue")

fderiv <- diff(pred)/diff(time)
lines(fderiv*100 ~ time[2:365], col = "red")
abline(v=as.numeric(which(fderiv == min(fderiv))), col="green")
abline(v=unique(ex_data$sos), col="green")

```

```{r compute_eos}

gdd_data$eos <- NA

library("doFuture")
registerDoFuture()
plan(multisession, workers = 10)

gdd_data <- foreach(s = unique(gdd_data$site), .combine = rbind) %dopar% {
  
  aux <- gdd_data[gdd_data$site == s,]

  years <- unlist(unique(aux$year))
  
  for(y in years){
    
    fit.dat <- aux %>% dplyr::filter(year == y)
    time <- fit.dat$doy
    fit.lm <- lm(tmean ~ cos(2*pi*doy/max(time)) + sin(2*pi*doy/max(time)), data = fit.dat)
    pred <- predict(fit.lm, newdata = list(doy = time))    
    fderiv <- diff(pred)/diff(time)
    
    aux[aux$year == y, "eos"] <- 
      as.numeric(which(fderiv == min(fderiv)))
  
  }
  
  aux

}
plan(sequential)
    
gdd_data %>%
  dplyr::select(site, latitude, sos, eos) %>%
  unique() %>%
  ggplot() +
  geom_boxplot(aes(y = eos, x = site, fill = latitude, color = latitude),
               alpha = 0.5) +
  geom_boxplot(aes(y = sos, x = site, fill = latitude, color = latitude),
               alpha = 0.5) +
  coord_cartesian(ylim = c(4,366), expand = FALSE, clip = "off") +
  scale_y_continuous(breaks = seq(5,365,30)) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = 'none')


```


```{r gdd_season,  fig.height = 30, fig.width = 10}

    
gdd_data %>%
  group_by(site, year) %>%
  dplyr::filter(doy >= sos & doy <= eos) %>%
  dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5, tmean, 0),
                gddw = cumsum(tmean_filt)) %>%
  ggplot(aes(x = doy, y = gddw)) +
  facet_wrap(~ site, ncol = 3) +
  geom_line(aes(group = year), alpha = 0.3, color = "darkred") +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  coord_cartesian(ylim = c(-700, 4700), xlim = c(0,340), expand = FALSE) +
  geom_boxplot(aes(y = -350, x = sos), width = 400) +
  geom_boxplot(aes(y = 4350, x = eos), width = 400) +
  geom_vline(xintercept = 172, linetype = "dotted")


```

### Using GDDacc

```{r gdd_pred}

days <- 1:200

gdd_predpower <- foreach(s = unique(gdd_data$site), .combine = rbind) %do% {
  
 pred_data <- gdd_data %>%
    group_by(year) %>%
    dplyr::filter(site == s) %>%
    dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5 & 
                                        doy >= sos & doy <= eos, tmean, 0),
                  gddw = cumsum(tmean_filt),
                  gddtot = max(gdd))
 
 r2 <- sapply(days, function(i){
   fit <- lm(scale(gddtot) ~ scale(gddw), data = pred_data %>% dplyr::filter(doy - sos == i))
   summary(fit)$r.squared})
 
 data.frame(site = s, day_sos = days, rsquared = r2)
  
}

gdd_predpower %>%
  group_by(day_sos) %>%
  dplyr::summarise(rsq = mean(rsquared), sd = sd(rsquared)) %>%
  ggplot(aes(x = day_sos, y = rsq)) +
  geom_line(color = "darkblue") +
  geom_ribbon(aes(ymin = rsq-sd, ymax = rsq+sd), fill = "darkblue", alpha = 0.2) + 
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  coord_cartesian(ylim = c(0,0.3), expand = FALSE) +
  labs(x = "Days since SOS (degC def.)")



```

```{r gdd_pred_bysite,  fig.height = 12, fig.width = 10}

solstice_eos <- gdd_data %>%
  dplyr::select(site, sos) %>%
  unique() %>%
  dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])


ggplot(aes(x = day_sos, y = rsquared),
      data = gdd_predpower %>% 
        dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])) +
  facet_wrap(~ source) +
  geom_line(aes(group = site), color = "darkblue") +
  geom_boxplot(aes(y = -0.05, x = 172-sos, group = 1), data = solstice_eos, width = 0.04) +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since SOS (degC def.)")



```

### Using GDDacc and GDDtrend (over the last week?)

```{r gdd_pred2}

days <- 7:200

library("doFuture")
registerDoFuture()
plan(multisession, workers = 10)

gdd_predpower2 <- foreach(s = unique(gdd_data$site), .combine = rbind) %dopar% {
  
 pred_data <- gdd_data %>%
  group_by(year) %>%
  dplyr::filter(site == s) %>%
  dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5 & 
                                      doy >= sos & doy <= eos, tmean, 0),
                gddw = cumsum(tmean_filt),
                gddtot = max(gdd),
                doysos = doy - sos) %>%
  ungroup() 
 
 r2 <- sapply(days, function(i){
   
   fit <- lm(gddtot ~ gddw + diff, data = pred_data %>%
               dplyr::filter(doysos %in% c(i, i-6)) %>%
               dplyr::select(doysos, gddw, gddtot,sos,eos) %>%
               mutate(doysos = ifelse(doysos==i, "gddw", "gddw_prev")) %>%
               tidyr::pivot_wider(names_from = doysos, values_from = gddw) %>%
               mutate(diff = gddw-gddw_prev))
   summary(fit)$r.squared})
 
 data.frame(site = s, day_sos = days, rsquared = r2)
  
}

plan(sequential)

gdd_predpower2 %>%
  group_by(day_sos) %>%
  dplyr::summarise(rsq = mean(rsquared), sd = sd(rsquared)) %>%
  ggplot(aes(x = day_sos, y = rsq)) +
  geom_line(color = "darkblue") +
  geom_ribbon(aes(ymin = rsq-sd, ymax = rsq+sd), fill = "darkblue", alpha = 0.2) + 
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since SOS (degC def.)")

```

```{r gdd_pred_bysite2,  fig.height = 12, fig.width = 10}

solstice_eos <- gdd_data %>%
  dplyr::select(site, sos) %>%
  unique() %>%
  dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])


ggplot(aes(x = day_sos, y = rsquared),
      data = gdd_predpower2 %>% 
        dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])) +
  facet_wrap(~ source) +
  geom_line(aes(group = site), color = "darkblue") +
  geom_line(aes(group = site), color = "darkblue", data = gdd_predpower %>% 
        dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1]), 
            linetype = "dashed", alpha = 0.1) +
  geom_boxplot(aes(y = -0.05, x = 172-sos, group = 1), data = solstice_eos, width = 0.04) +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since SOS (degC def.)")



```

### A different definition for SOS

```{r compute_sos2}

library("doFuture")
registerDoFuture()
plan(multisession, workers = 10)

gdd_data2 <- foreach(s = unique(gdd_data$site), .combine = rbind) %dopar% {
  
  aux <- gdd_data[gdd_data$site == s,]

  years <- unlist(unique(aux$year))
  
  for(y in years){
    
    fit.dat <- aux %>% dplyr::filter(year == y)
    time <- fit.dat$doy
    fit.lm <- lm(tmean ~ cos(2*pi*doy/max(time)) + sin(2*pi*doy/max(time)), data = fit.dat)
    pred <- predict(fit.lm, newdata = list(doy = time))    
    fderiv <- diff(pred)/diff(time)
    
    aux[aux$year == y, "sos_harmonic"] <- 
      as.numeric(which(fderiv == max(fderiv)))
  
  }
  
  aux

}
plan(sequential)
    
gdd_data2 %>%
  dplyr::select(site, latitude, sos, sos_harmonic, eos) %>%
  unique() %>%
  ggplot() +
  geom_boxplot(aes(y = eos, x = site, fill = "#AC80A0", color = "#AC80A0"),
               alpha = 0.5) +
  geom_boxplot(aes(y = sos, x = site, fill = "#005f73", color = "#005f73"),
               alpha = 0.5) +
  geom_boxplot(aes(y = sos_harmonic, x = site, fill = "#AC80A0", color = "#AC80A0"),
               alpha = 0.5) +
  coord_cartesian(ylim = c(4,366), expand = FALSE, clip = "off") +
  scale_y_continuous(breaks = seq(5,365,30)) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = 'none')


```

```{r gdd_pred3}

days <- 1:200

gdd_predpower <- foreach(s = unique(gdd_data2$site), .combine = rbind) %do% {
  
 pred_data <- gdd_data2 %>%
    group_by(year) %>%
    dplyr::filter(site == s) %>%
    dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5 & 
                                        doy >= sos_harmonic & doy <= eos, tmean, 0),
                  gddw = cumsum(tmean_filt),
                  gddtot = max(gdd))
 
 r2 <- sapply(days, function(i){
   fit <- lm(scale(gddtot) ~ scale(gddw), data = pred_data %>% dplyr::filter(doy - sos_harmonic == i))
   summary(fit)$r.squared})
 
 data.frame(site = s, day_sos = days, rsquared = r2)
  
}

gdd_predpower %>%
  group_by(day_sos) %>%
  dplyr::summarise(rsq = mean(rsquared), sd = sd(rsquared)) %>%
  ggplot(aes(x = day_sos, y = rsq)) +
  geom_line(color = "darkblue") +
  geom_ribbon(aes(ymin = rsq-sd, ymax = rsq+sd), fill = "darkblue", alpha = 0.2) + 
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since SOS (harm. def.)")



```

```{r gdd_pred_bysite3,  fig.height = 12, fig.width = 10}

solstice_eos <- gdd_data2 %>%
  dplyr::select(site, sos_harmonic) %>%
  unique() %>%
  dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])


ggplot(aes(x = day_sos, y = rsquared),
      data = gdd_predpower %>% 
        dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])) +
  facet_wrap(~ source) +
  geom_line(aes(group = site), color = "darkblue") +
  geom_boxplot(aes(y = -0.05, x = 172-sos_harmonic, group = 1), data = solstice_eos, width = 0.04) +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since SOS (harm. def.)")



```

### What if SOS = 1st Jan, ie tree accumulate memory anyway

```{r gdd_pred4}

days <- 1:365


gdd_predpower <- foreach(s = unique(gdd_data2$site), .combine = rbind) %do% {
  
 pred_data <- gdd_data2 %>%
    group_by(year) %>%
    dplyr::filter(site == s) %>%
    dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5 & 
                                        doy >= 1 & doy <= eos, tmean, 0),
                  gddw = cumsum(tmean_filt),
                  gddtot = max(gdd))
 
 r2 <- sapply(days, function(i){
   fit <- lm(gddtot ~ gddw, data = pred_data %>% dplyr::filter(doy == i))
   summary(fit)$r.squared})
 
 data.frame(site = s, day_sos = days, rsquared = r2)
  
}

gseason <- gdd_data2 %>%
  dplyr::select(site, eos, sos, sos_harmonic) %>%
  unique() %>%
  dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])

eos_med <- gseason %>%
  summarise(eos = median(eos))

gdd_predpower %>%
  group_by(day_sos) %>%
  dplyr::summarise(rsq = mean(rsquared), sd = sd(rsquared)) %>%
  ggplot(aes(x = day_sos, y = rsq)) +
  geom_line(color = "darkblue") +
  geom_ribbon(aes(ymin = rsq-sd, ymax = rsq+sd), fill = "darkblue", alpha = 0.2) + 
  geom_boxplot(aes(y = -0.05, x = eos, group = 1), data = gseason, width = 0.04) +
  geom_boxplot(aes(y = -0.05, x = sos, group = 1), data = gseason, width = 0.03) + 
  geom_boxplot(aes(y = -0.02, x = sos_harmonic, group = 1), data = gseason, width = 0.03) + 
  geom_vline(aes(xintercept = eos), linetype = "dashed", data = eos_med, color = "grey") +
  geom_vline(xintercept = 172, linetype = "dotted") +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since 1st Jan")



```

```{r gdd_pred_bysite4,  fig.height = 12, fig.width = 10, eval = FALSE}



eos_med <- gseason %>%
  group_by(source) %>%
  summarise(eos = median(eos))


ggplot(aes(x = day_sos, y = rsquared),
      data = gdd_predpower %>% 
        dplyr::mutate(source = stringr::str_split(site, "_", simplify = T)[, 1])) +
  facet_wrap(~ source) +
  geom_line(aes(group = site), color = "darkblue") +
  geom_vline(xintercept = 172, linetype = "dotted") +
  geom_boxplot(aes(y = -0.05, x = sos, group = 1), data = gseason, width = 0.04) + 
  geom_boxplot(aes(y = -0.05, x = eos, group = 1), data = gseason, width = 0.04) +
  geom_vline(aes(xintercept = eos), linetype = "dashed", data = eos_med, color = "grey") +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since 1st Jan")

```

### SOS = 1st Jan + GDDtrend

```{r gdd_pred5}

days <- 7:365

library("doFuture")
registerDoFuture()
plan(multisession, workers = 10)

gdd_data$sos <- 0

gdd_predpower2 <- foreach(s = unique(gdd_data$site), .combine = rbind) %dopar% {
  
 pred_data <- gdd_data %>%
  group_by(year) %>%
  dplyr::filter(site == s) %>%
  dplyr::mutate(tmean_filt = ifelse(tmean <= 35 & tmean >=5 & 
                                      doy >= sos & doy <= eos, tmean, 0),
                gddw = cumsum(tmean_filt),
                gddtot = max(gdd),
                doysos = doy - sos) %>%
  ungroup() 
 
 r2 <- sapply(days, function(i){
   
   fit <- lm(gddtot ~ gddw + diff, data = pred_data %>%
               dplyr::filter(doysos %in% c(i, i-6)) %>%
               dplyr::select(doysos, gddw, gddtot,sos,eos) %>%
               mutate(doysos = ifelse(doysos==i, "gddw", "gddw_prev")) %>%
               tidyr::pivot_wider(names_from = doysos, values_from = gddw) %>%
               mutate(diff = gddw-gddw_prev))
   summary(fit)$r.squared})
 
 data.frame(site = s, day_sos = days, rsquared = r2)
  
}

plan(sequential)

eos_med <- gseason %>%
  summarise(eos = median(eos))

gdd_predpower2 %>%
  group_by(day_sos) %>%
  dplyr::summarise(rsq = mean(rsquared), sd = sd(rsquared)) %>%
  ggplot(aes(x = day_sos, y = rsq)) +
  geom_line(color = "darkblue") +
  geom_ribbon(aes(ymin = rsq-sd, ymax = rsq+sd), fill = "darkblue", alpha = 0.2) + 
  geom_boxplot(aes(y = -0.05, x = eos, group = 1), data = gseason, width = 0.04) +
  geom_vline(aes(xintercept = eos), linetype = "dashed", data = eos_med, color = "grey") +
  geom_vline(xintercept = 172, linetype = "dotted") +
  theme_bw() +
  theme(legend.position = 'none',
        strip.background = element_blank(),
        panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  labs(x = "Days since 1st Jan")

```